In [1]:
from ipywidgets import Textarea
import io

if 'input' in globals():
    del input

class custom_input():
    def __init__(self):
        self.__sio = io.StringIO('')
        self.shell = get_ipython()
        if self.shell.events.callbacks['pre_run_cell'] != []:
            self.shell.events.callbacks['pre_run_cell'] = []
        self.shell.events.register('pre_run_cell', self.pre_run_cell)

    def __call__(self):
        return self.__sio.readline().strip()

    def pre_run_cell(self, info):
        text = self.shell.user_ns.get('text_area', None).value
        self.__sio = io.StringIO(text)
input = custom_input()

text_area = Textarea()
display(text_area)

Textarea(value='')

In [538]:
n = 33

a = []
for i in range(2, n + 1):
    nn = n
    while True:
        if nn < k:
            break
        if nn%i == 0:
            nn = nn//i
        else:
            nn = nn - i
    if nn == 1:
        a.append(i)

a

[2, 4, 8, 16, 32, 33]

In [539]:
x = factorize(n - 1)

In [540]:
b = 1
for i in range(len(x)):
    b *= (x[i][1] + 1)
b

6

In [541]:
x = factorize(int(np.sqrt(n)))

In [542]:
c = 1
for i in range(len(x)):
    c *= (x[i][1] + 1)
c

2

In [544]:
len(a)

6

In [499]:

def factorize(n):
    ## 素因数分解
    # arr = factorize(20)
    # arr == [[2, 2], [5, 1]]
    
    result = []
    tmp = n
    for k in range(2, int(n ** 0.5) + 1):
        cnt = 0
        while tmp % k == 0:
            cnt += 1
            tmp //= k
        if cnt > 0:
            result.append([k, cnt])
    if tmp != 1:
        result.append([tmp, 1])
    return result

# E

In [378]:
n, k, c = list(map(int, input().split()))
s = input()
import numpy as np
o = np.where(np.array(list(s)) == "o")[0]
print(o)
a = np.diff(o) >= c
print(a)
b = a[:-1] + 0 + a[1:]
s = np.where(b == 2)[0]
for oo in o[s + 1]:
    print(oo + 1)

[0 1 3 4]
[False False False]


In [406]:
n, k, c = list(map(int, input().split()))
s = input()
import numpy as np
o = np.where(np.array(list(s)) == "o")[0]

In [407]:
now = 0

In [449]:
dp = [0] * n
ma = [0] * n
co = [0] * n
for now in range(-c, 0):
    if s[now] == "o":
        dp[now] = 1
        ma[now] = 1
for now in range(-n, -c)[::-1]:
    print(now)
    ma[now + 1] = 
    if s[now] == "o":
        dp[now] = 1 + ma[now]
        ma += 1

In [454]:
s

'ooxxxoxxxoo'

In [453]:
o

array([ 0,  1,  5,  9, 10])

In [451]:
dp

[4, 3, 0, 0, 0, 2, 0, 0, 0, 1, 1]

In [452]:
dp

[4, 3, 0, 0, 0, 2, 0, 0, 0, 1, 1]

In [422]:
s

'ooxxxoxxxoo'

In [ ]:
for i in range(len(o)):
    

In [408]:
o

array([ 0,  1,  5,  9, 10])

In [400]:
s

'ooxoo'

In [401]:
k

2

In [402]:
c

3

In [384]:
dp = np.zeros([n, k])

In [394]:
now = 0

In [398]:
now = 0
dp[0,0] = 1


In [399]:
now += 1

In [ ]:
dp[now, 0] = 

In [387]:
dp[1,0]

array([[1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [382]:
dp

[0, 0, 0, 0, 0]

In [383]:
dp[0]

0

In [370]:
n

5

In [371]:
k

2

In [372]:
c

3

In [373]:
o

array([0, 1, 3, 4])

In [376]:
a

array([False, False, False])

In [375]:
a

array([False, False, False])

# D

In [318]:
import numpy as np
k = int(input()) - 1
if len(str(k)) == 1:
    print(k + 1)
else:

    jjj = 0
    ans = [0]

    num = 0
    dps = []
    dp = [1] * 10
    dp[0] = 0

    flag = False
    for i in range(len(dp)):
        num += dp[i]
        if num > k:
            flag = True
            break

    dp[0] = 1
    dps.append(dp)

    flag = False
    while True:
        dp = [0] * 10
        dp[0] = 0
        for i in range(1, 9):
            dp[i] = sum(dps[-1][i - 1 : i + 2])
        dp[9] = dps[-1][8] + dps[-1][9]


        for i in range(len(dp)):
            num += dp[i]
            if num > k:
                flag = True
            if flag:
                num -= dp[i]
                break
        if flag:
            break
        dp[0] = dps[-1][0] + dps[-1][1]
        dps.append(dp)

    ans = [i]
    k = k - num
    jjj += 1

#     print(k)
    try:
        while True:
#             print(k)
            num = 0
            ii = i
            for i in range(max([ii - 1, 0]), ii + 2):
            #     print(i)
                if num + dps[-1][i]> k:
                    break
                else:
                    num += dps[-1][i]

            ans.append(i)
            k -= num
            dps = dps[:-1]
#             print(k)
            if k == 0 and len(dps) > 0:
                aaa = i - 1
                while True:    
                    if aaa < 0 :
                        aaa = 0
                    ans += [aaa]
                    aaa -= 1
                    dps = dps[:-1]
                    if len(dps) == 0:
                        break
                aaaaaa
    except:
        print("".join(map(str, ans)))

23


# C

In [36]:
n, k = list(map(int, input().split()))
print(min([n%k, k - n%k]))

0


# B

In [26]:
import numpy as np
n, m = list(map(int, input().split()))
a = list(map(int, input().split()))
if sum(np.array(a) >= sum(a)/4/m) >= m:
    print("Yes")
else:
    print("No")

Yes


# A

In [7]:
x, y, z = list(map(int, input().split()))
print(z, x, y)

3 1 2
