In [1]:
from ipywidgets import Textarea
import io

if 'input' in globals():
    del input

class custom_input():
    def __init__(self):
        self.__sio = io.StringIO('')
        self.shell = get_ipython()
        if self.shell.events.callbacks['pre_run_cell'] != []:
            self.shell.events.callbacks['pre_run_cell'] = []
        self.shell.events.register('pre_run_cell', self.pre_run_cell)

    def __call__(self):
        return self.__sio.readline().strip()

    def pre_run_cell(self, info):
        text = self.shell.user_ns.get('text_area', None).value
        self.__sio = io.StringIO(text)
input = custom_input()

text_area = Textarea()
display(text_area)

Textarea(value='')

# A

In [2]:
import numpy as np
h, w = list(map(int, input().split()))
ss = []
for _ in range(h):
    s = input()
    s = s.replace(".", "0").replace("#", "1")
    s = list(map(int, list(s)))
    ss.append(s)
ss = np.array(ss)
    

dp = np.zeros((h, w)).astype(np.int32)
if ss[0,0] == 1:
    dp[0,0] = 1
    

for kh in range(h):
    for kw in range(w):
#         print(kh, kw)
#         print(dp)
        if kh == 0 and kw == 0:
            continue
        if kh == 0:
            a = 9999
        else:
            if ss[kh - 1, kw] == 0 and ss[kh, kw] == 1:
                a = dp[kh - 1, kw] + 1
            else:
                a = dp[kh - 1, kw]

        if kw == 0:
            b = 9999
        else:
            if ss[kh, kw - 1] == 0 and ss[kh, kw] == 1:
                b = dp[kh, kw - 1] + 1
            else:
                b = dp[kh, kw - 1]

        dp[kh, kw] = min([a, b])

print(dp[-1, -1])

4


# B

## tryしたけど何もわからなかった残骸

In [108]:
from ipywidgets import Textarea
import io

if 'input' in globals():
    del input

class custom_input():
    def __init__(self):
        self.__sio = io.StringIO('')
        self.shell = get_ipython()
        if self.shell.events.callbacks['pre_run_cell'] != []:
            self.shell.events.callbacks['pre_run_cell'] = []
        self.shell.events.register('pre_run_cell', self.pre_run_cell)

    def __call__(self):
        return self.__sio.readline().strip()

    def pre_run_cell(self, info):
        text = self.shell.user_ns.get('text_area', None).value
        self.__sio = io.StringIO(text)
input = custom_input()

text_area = Textarea()
display(text_area)

Textarea(value='')

In [ ]:
%%time
import numpy as np

n = int(input())
a = list(map(int, list(input())))


n = 100000
a = np.random.randint(0, 4, n)

In [119]:
a

array([2, 3, 3, ..., 0, 0, 3])

In [122]:
%%time

n = 100000
a = np.random.randint(1, 4, n)
x = a
while len(x) > 1:
    x = np.abs(np.diff(x))
print(x[0])

0
CPU times: user 6.2 s, sys: 71.1 ms, total: 6.27 s
Wall time: 6.4 s


In [221]:
%%time

n = 5
a = np.random.randint(1, 4, n)
x = a
while len(x) > 1:
    x = np.abs(np.diff(x))
print(x[0])

0
CPU times: user 397 µs, sys: 176 µs, total: 573 µs
Wall time: 440 µs


In [224]:
np.abs(np.diff(a))

array([1, 1, 0, 2])

In [225]:
a

array([1, 2, 3, 3, 1])

In [232]:
N = int(input())
a = list(map(int, list(input())))

while N != 0:
	print(digit)
	digit = 1
	while digit < N // 2:
		digit *= 2

	x = []
	for i in range(digit, N):
		x.append(abs(a[i - digit] - a[i]))

	a = x
	N -= digit
	if len(x) == 1:
		break

print(a[0])


1
8
0


In [168]:
%%time
n = 10
a = np.random.randint(1, 4, n)
x = a - 1

CPU times: user 63 µs, sys: 14 µs, total: 77 µs
Wall time: 70.1 µs


In [169]:
a = "".join(x.astype(str))

In [170]:
x = a

In [184]:
from itertools import combinations, repeat, permutations, 

'210'

In [ ]:
dic = {}
def step(z):
    if z in dic.keys():
        dic[z] = 

In [ ]:
while len(x) > 1:
    x = np.abs(np.diff(x))
print(x[0])

CPU times: user 278 µs, sys: 131 µs, total: 409 µs
Wall time: 258 µs


In [104]:
%%time

x = a
dic = {}
for i in range(1, n):
    y = [-1] * (n - i)
    for k in range(n - i):
        y[k] = abs(x[k] - x[k+1])
    x = y
#     print(x)


CPU times: user 4.4 s, sys: 16.3 ms, total: 4.41 s
Wall time: 4.46 s


In [105]:
x

[0]

In [59]:
x[k : k + 1]

array([3])

In [56]:
a[k : k + 1]

array([1])

In [55]:
a

array([1, 3, 3, 2, 3, 0, 3, 2, 0, 2, 0, 0, 2, 1, 1, 2, 0, 1, 1, 1, 2, 2,
       2, 3, 1, 1, 2, 0, 0, 2, 2, 0, 0, 2, 0, 1, 3, 1, 3, 0, 2, 2, 2, 0,
       3, 0, 3, 0, 1, 2, 1, 2, 1, 3, 3, 2, 1, 2, 0, 0, 2, 3, 1, 0, 3, 3,
       3, 2, 1, 2, 2, 2, 1, 3, 1, 2, 2, 0, 1, 3, 2, 0, 2, 2, 2, 1, 2, 1,
       0, 1, 0, 3, 0, 2, 3, 1, 1, 0, 1, 2, 1, 0, 3, 3, 2, 3, 1, 0, 1, 1,
       0, 3, 0, 1, 2, 0, 3, 0, 3, 0, 3, 1, 1, 2, 1, 3, 2, 2, 1, 1, 2, 1,
       2, 3, 0, 2, 0, 2, 3, 3, 2, 2, 1, 2, 1, 2, 3, 1, 2, 2, 1, 3, 0, 0,
       2, 1, 3, 2, 2, 1, 3, 3, 3, 0, 1, 2, 0, 0, 2, 1, 3, 3, 0, 0, 1, 3,
       1, 2, 1, 0, 1, 2, 0, 0, 1, 2, 3, 1, 1, 1, 0, 1, 1, 3, 1, 2, 0, 2,
       2, 2, 3, 3, 3, 3, 0, 3, 3, 1, 0, 1, 1, 2, 1, 0, 2, 2, 2, 2, 2, 1,
       3, 3, 3, 2, 3, 2, 2, 3, 1, 2, 1, 1, 2, 3, 3, 0, 2, 1, 2, 1, 1, 2,
       3, 2, 3, 3, 0, 2, 1, 3, 0, 1, 2, 3, 1, 2, 1, 1, 0, 1, 2, 1, 2, 0,
       0, 2, 0, 2, 0, 2, 1, 0, 0, 3, 2, 3, 2, 0, 0, 0, 3, 3, 2, 0, 1, 3,
       0, 0, 0, 1, 0, 0, 1, 0, 3, 0, 3, 2, 2, 0, 2,

In [59]:
kh

1

In [60]:
kw

3

In [57]:
dp

array([[9999, 9999, 9999, 9999],
       [9999,    1,    0,    0],
       [9999,    0,    0,    0],
       [9999,    0,    0,    0]], dtype=int32)

In [35]:
dp[kh - 1, kw]

NameError: name 'kh' is not defined